sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2 
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/ebooklib.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git

- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt
- asciidoctor -a toc,idprefix=xx_,version=$VERSION -b xhtml5 -T ./asciidoctor-htmlbook/htmlbook-autogen/
  -d book book.asciidoc -o book.html
- git clone https://github.com/gitenberg-dev/HTMLBook

# make book.html available to jinja2 environment by putting it into templates
- cp book.html asciidoctor-htmlbook/gitberg-machine/templates/

- /usr/bin/python asciidoctor-htmlbook/gitberg-machine/machine.py -o . -m metadata.yaml book.html
- xsltproc -stringparam external.assets.list " " ./HTMLBook/htmlbook-xsl/epub.xsl book.html
- cp ./HTMLBook/stylesheets/epub/epub.css OEBPS
- if [ -e cover.jpg ]; then cp cover.jpg OEBPS/cover.jpg; fi
# look for first images directory and one found, copy over to ./OEBPS
- find . -name images -type d | head -n 1 | xargs -I {} mv {} ./OEBPS/
- zip -rX book.epub mimetype
- zip -rX book.epub OEBPS/ META-INF/
- if test -d "OEBPS/images/"; then zip -rX book.epub OEBPS/images/ ;fi
- mv book.epub Moby-Dick-Or-The-Whale.epub
- ebook-convert Moby-Dick-Or-The-Whale.epub Moby-Dick-Or-The-Whale.mobi
- xvfb-run ebook-convert Moby-Dick-Or-The-Whale.epub Moby-Dick-Or-The-Whale.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rWrVv0TXfAuniPLqBu3gqbUhpoWSgnMq6oJkHykacAApsy3qbowiOM0urJ2+1e2hSIwGExqiH8xEmfwwON+XkuW2rPVVHJ644s0cashmEUMzr9wBj2+wWWs7m0kv3HgNizPYR+tIv+6PCd9OfgSybfwr+cUBsT8hVXQuXYg5YYGVmAq6XTYbG3ZVi6QAPfoKtQweowtLC21Zwg160CuTLOVlh436HmQmfK4ycuqUTZ0NsndAQQvbpe4kq22UhtGfjDK+l+GtRJbcwfJMMWuA26MtEXIul1ByXiuZ95t/oA2uwswl7f2jrGiclxX491TE4UKmfYV8B0lFBanL6XuDL4X1kcZIUjFu9X/wZkahY+ivdvrfGkbxkOya3hAYqknbO5ZePVIivhSDdMvFCBv2mZUk5aOe39pvXSpf8X4rgoyx8ed7dWzfoWup8zyMYY9Rf+RNreY5o/w783qYUq54EXeZTC79cvIYOAliF4C6KrUFG+p4mOw1iRI1QjhBgVh5901tOJpMMO/IFRCvPdMxZo1kqDnaGJZ2/5aZG34w2G/SUUm0DnXBh24tUDGQDH+bvknNR688uqRZZtzC54XWRv8r5fEwKkP/Eo+ItPppARwzLjfQMKkRp6VAXvq0I5t/FEtvTASSaASS8cD1DxwyGfK78v1bS1jWJPuh6B4z5Iw=
  file:
    - Moby-Dick-Or-The-Whale.epub
    - Moby-Dick-Or-The-Whale.mobi
    - Moby-Dick-Or-The-Whale.pdf
  "on":
    repo: GITenberg/Moby-Dick--Or-The-Whale_2701
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre